### ISSUE TITLE
How to use this in a web server - share one global connection?

### ISSUE THREAD

**Issue by DallanQ** [bsphere/le_go#3]
Just wondering what's the best way to use this in a web server. Should I create a single connection at startup and share it as a global variable among multiple go-routines handling requests, or should I create a new connection at the start of each request?

Thank-you for creating this library.

**Comment by bsphere** [comment]
I think that it depends on how you want your system to work..

I would share one logger between goroutines, there's only cost and no benefit in opening a TCP connection for each incoming HTTP request.. I usually do that by passing a [context](https://blog.golang.org/context) to the HTTP handlers.

**Comment by DallanQ** [comment]
perfect - thanks!
